AWSTemplateFormatVersion: 2010-09-09
Description: OpsWorks stack and Deployment Pipeline in CodePipeline
Resources:
  CPOpsDeploySecGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Lets you manage OpsWorks instances deployed to by CodePipeline
  CPOpsDeploySecGroupIngressHTTP:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      IpProtocol: tcp
      FromPort: "80"
      ToPort: "80"
      CidrIp: 0.0.0.0/0
      GroupId: !GetAtt CPOpsDeploySecGroup.GroupId
  CPOpsDeploySecGroupIngressSSH:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      IpProtocol: tcp
      FromPort: "22"
      ToPort: "22"
      CidrIp: 0.0.0.0/0
      GroupId: !GetAtt CPOpsDeploySecGroup.GroupId

Outputs:
  CPOpsDeploySecGroup:
    Description: CPOpsDeploySecGroup.GroupId
    Value: !GetAtt CPOpsDeploySecGroup.GroupId
    Export:
      Name: CPOpsDeploySecGroupGroupId
